server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  web:
    resources:
      add-mappings: false

  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 100
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/tech?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expire-length: 3600000
      refresh-token-expire-length: 1209600000

kakao:
  auth:
    token-uri: https://kauth.kakao.com/oauth/token
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: http://localhost:3000/auth/kakao/callback

  user:
    profile-uri: https://kapi.kakao.com/v2/user/me

naver:
  auth:
    token-uri: https://nid.naver.com/oauth2.0/token
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: http://localhost:3000/auth/naver/callback

  user:
    profile-uri: https://openapi.naver.com/v1/nid/me

rss-feed:
  scheduler:
    reset: "0 0 3 * * *"       # 매일 새벽 3시 실행
    read:  "0 0/5 3-5 * * *"   # 매일 새벽 3시부터 5시까지 5분 간격 실행

slack:
  webhook:
    server-error-url: ${SLACK_SERVER_ERROR_URL}
    rss-reader-url: ${SLACK_RSS_READER_URL}

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**