server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  web:
    resources:
      add-mappings: false

  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 100
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/tech_local?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: tech_local
    password: local!32

security:
  jwt:
    token:
      secret-key: tech-posts-local-secret-key
      access-token-expire-length: 3600000 # 1 hour for access token
      refresh-token-expire-length: 1209600000 # 2 weeks for refresh token

kakao:
  auth:
    token-uri: https://kauth.kakao.com/oauth/token
    client-id: e2645956d195649b289525e32a89ecab
    client-secret: e2645956d195649b289525e32a89ecab
    redirect-uri: http://localhost:3000/auth/kakao/callback

  user:
    profile-uri: https://kapi.kakao.com/v2/user/me

naver:
  auth:
    token-uri: https://nid.naver.com/oauth2.0/token
    client-id: fQ41lAPpIHNYkUrtChyx
    client-secret: g9XJR2wnKR
    redirect-uri: http://localhost:3000/auth/naver/callback

  user:
    profile-uri: https://openapi.naver.com/v1/nid/me

rss-feed:
  scheduler:
    reset: "0 */1 * * * *"     # 3분 마다 실행
    read:  "10 * * * * *"      # 10초 마다 실행

slack:
  webhook:
    server-error-url: https://hooks.slack.com/services/ # FIX ME
    rss-reader-url: https://hooks.slack.com/services/ # FIX ME

logging:
  level:
    org.hibernate.SQL: debug                  # 실행 query 확인
    org.hibernate.orm.jdbc.bind: trace # query parameter log
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.type.descriptor.sql: trace

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**